-- AlterTable
ALTER TABLE `user` ADD COLUMN `city` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `firstName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `lastName` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `vkId` VARCHAR(191) NOT NULL DEFAULT '';
